### ISSUE TITLE
Интеграция перестала работать, баги

### ISSUE THREAD

**Issue by sc16me** [dentra/ha-pesc#11]
Более недели как перестала работать интеграция на дачном сервере HA. Вводные данные такие:
На домашнем сервере учетка на меня, одна квартира, двухтарифный счетчик.
На дачном сервере учетка pesc на тещу, следовательно в учетке два дома - квартира и дача. Квартира - двухтарифный счетчик, с автоматической отправкой показаний. Дача - обычный двухтарифный счетчик, показания отправлялись в ручную (а с недавних пор через интеграцию).
Примерно неделю назад интеграции у меня дома и на даче перестали работать на сутки. Затем домашняя ожила, но добавила новые объекты (показания и стоимость), тем самым старые объекты стали недоступны. Удалил старые объекты, новые переименовал, в том числе поменял id на от старых чтобы не переписывать автоматизации. Вроде все хорошо.
На дачном сервере ситуация с новыми объектами аналогичная, все сделал так же, но фактически: данные с квартиры тещи - объекты есть, но данным по ним нет. Иногда данные о стоимости кВч появляются, но сразу пропадают. По даче аналогично - объекты есть, но данным по ним нет.
Интеграцию переустанавливать, все что можно обновил (debian + ha), не помогает.

По домашнему серверу вроде вопросов нет, вроде все работает, а вот по дачному включил debug и вот вывод:
```
Регистратор: homeassistant.components.sensor
Источник: helpers/entity_platform.py:372
интеграция: Сенсор (документация, проблемы)
Первое сообщение: 15:26:37 (1 сообщений)
Последнее сообщение: 15:26:37

Error while setting up pesc platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 372, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 631, in async_add_entities
    for entity in new_entities:
  File "/config/custom_components/pesc/sensor.py", line 40, in <genexpr>
    PescMeterSensor(coordinator, m, diag) for m in coordinator.api.meters
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pesc/sensor.py", line 183, in __init__
    super().__init__(coordinator, meter)
  File "/config/custom_components/pesc/sensor.py", line 138, in __init__
    self._update_state_attributes()
  File "/config/custom_components/pesc/sensor.py", line 232, in _update_state_attributes
    rate = tariff.rate(self.meter.scale_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pesc/pesc_api.py", line 146, in rate
    return "/".join(self.rates)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, float found



Регистратор: homeassistant.components.sensor
Источник: helpers/entity_platform.py:598
интеграция: Сенсор (документация, проблемы)
Первое сообщение: 15:26:37 (2 сообщений)
Последнее сообщение: 15:26:37

Error adding entity sensor.pesc_electricity_day_rub for domain sensor with platform pesc
Error adding entity sensor.pesc_electricity_night_rub for domain sensor with platform pesc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1362, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 533, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pesc/sensor.py", line 339, in native_value
    return tariff.rate(self.meter.scale_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pesc/pesc_api.py", line 146, in rate
    return "/".join(self.rates)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, float found



Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.pesc.pesc_api
Источник: custom_components/pesc/pesc_api.py:139
интеграция: ПетроЭлектросСбыт (документация, проблемы)
Первое сообщение: 15:26:37 (3 сообщений)
Последнее сообщение: 15:26:37

Unsupported tariff "Электроэнергия" kind "Однотарифный"



Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.pesc
Источник: custom_components/pesc/__init__.py:94
интеграция: ПетроЭлектросСбыт (документация, проблемы)
Первое сообщение: 15:26:23 (1 сообщений)
Последнее сообщение: 15:26:23

Ошибка вызова API: I/O error on POST request for "https://eb-ul-palmira.spb19-ibfl-k8s-cloud.interrao.ru/ReportFormData/get.do": Remote host terminated the handshake; nested exception is javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake



Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.pesc.pesc_client
Источник: custom_components/pesc/pesc_client.py:189
интеграция: ПетроЭлектросСбыт (документация, проблемы)
Первое сообщение: 15:26:23 (1 сообщений)
Последнее сообщение: 15:26:23

ClientError[url=https://ikus.pesc.ru/api/v7/accounts, code=96, message=I/O error on POST request for "https://eb-ul-palmira.spb19-ibfl-k8s-cloud.interrao.ru/ReportFormData/get.do": Remote host terminated the handshake; nested exception is javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake, cause=]


```
![Снимок экрана 2024-07-08 в 15 35 56](https://github.com/dentra/ha-pesc/assets/1618809/41e98a83-933f-4855-8d8d-1da5754c17db)
![Снимок экрана 2024-07-08 в 15 34 03](https://github.com/dentra/ha-pesc/assets/1618809/5b9b94b9-e14b-4a35-9988-1fb241009479)
Ну и мелкий косячок на закуску ;):
![Снимок экрана 2024-07-08 в 15 33 54](https://github.com/dentra/ha-pesc/assets/1618809/e965d9a7-3c58-457c-a4b8-3edd872ed85f)

**Comment by dentra** [comment]
Походу поменяли API, буду разбираться

**Comment by dentra** [comment]
в релизе
