### ISSUE TITLE
Не может получить первоначальные данные из ЛК

### ISSUE THREAD

**Issue by t2029** [dentra/ha-pesc#18]
<img width="528" alt="2" src="https://github.com/user-attachments/assets/305b4aa4-3691-4b44-8502-9f276ecfd2de">
<img width="533" alt="1" src="https://github.com/user-attachments/assets/431535b6-495b-4bc9-8102-5adda7b18f75">

Лог:

2024-09-06 00:58:50.955 ERROR (MainThread) [custom_components.pesc.pesc_client] ClientError[url=https://ikus.pesc.ru/api/v8/accounts/1872197/address, code=355, message=Для текущего провайдера операция не поддерживается, cause=]
2024-09-06 01:00:11.510 ERROR (MainThread) [custom_components.pesc] Unexpected error fetching pesc data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pesc/__init__.py", line 77, in _async_update_data
    await self.relogin_and_fetch_(False)
  File "/config/custom_components/pesc/__init__.py", line 84, in relogin_and_fetch_
    await self.api.async_fetch_all()
  File "/config/custom_components/pesc/pesc_api.py", line 233, in async_fetch_all
    await self.async_fetch_data()
  File "/config/custom_components/pesc/pesc_api.py", line 255, in async_fetch_data
    await asyncio.gather(*(self._load_account(account) for account in accounts))
  File "/config/custom_components/pesc/pesc_api.py", line 260, in _load_account
    await asyncio.gather(
  File "/config/custom_components/pesc/pesc_api.py", line 282, in _load_meters
    ind = MeterInd(acc, met, met_ind)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pesc/pesc_api.py", line 60, in __init__
    self.date = datetime.strptime(ind["previousReadingDate"], "%d.%m.%Y").date()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None

**Comment by t2029** [comment]
Как я вижу, здесь две проблемы:
1) None вместо string при инициализации 
self.date = datetime.strptime(ind["previousReadingDate"], "%d.%m.%Y").date()
Залечил
self.date = datetime.strptime("01.01.2020", "%d.%m.%Y").date()
2) В одном из лицевых счетов (конкретно Газпроммежрегионгаз) не указан адрес. Из-за чего скрипт вылетает с ошибкой. Хотя можно ее и обработать.
Удалил этот лицевой счет из ЛК ПЭС.
